
#requiresdefine   'PETSC_HAVE_FORTRAN'
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = trlanczosf.c
SOURCEF  =
SOURCEH  = 
DIRS     =
LIBBASE  = libslepcsvd
LOCDIR   = src/svd/impls/trlanczos/ftn-auto/
include ${SLEPC_DIR}/conf/slepc_common
