
#requiresdefine   'PETSC_HAVE_FORTRAN'
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = pepsetupf.c pepmonf.c pepsolvef.c pepoptsf.c pepdefaultf.c pepbasicf.c
SOURCEF  =
SOURCEH  = 
DIRS     =
LIBBASE  = libslepcpep
LOCDIR   = src/pep/interface/ftn-auto/
include ${SLEPC_DIR}/conf/slepc_common
