
#requirespackage   'PETSC_HAVE_FORTRAN'
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = lsparamsf.c
OBJSC    = lsparamsf.o
SOURCEF  =
SOURCEH  = 
DIRS     =
LIBBASE  = libpetscsnes
LOCDIR   = src/snes/impls/ls/ftn-auto/
include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test
