
#requirespackage   'PETSC_HAVE_FORTRAN'
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = dgcoorf.c dpointf.c dellipsef.c dgpausef.c dpausef.c dtextgsf.c dlinegwf.c dflushf.c dviewpf.c dlinewf.c dclearf.c dlinef.c dtextsf.c dsflushf.c dsclearf.c drawf.c dsetpausef.c drectf.c dmousef.c dpointsf.c dcoorf.c dbufff.c dtrif.c
OBJSC    = dgcoorf.o dpointf.o dellipsef.o dgpausef.o dpausef.o dtextgsf.o dlinegwf.o dflushf.o dviewpf.o dlinewf.o dclearf.o dlinef.o dtextsf.o dsflushf.o dsclearf.o drawf.o dsetpausef.o drectf.o dmousef.o dpointsf.o dcoorf.o dbufff.o dtrif.o
SOURCEF  =
SOURCEH  = 
DIRS     =
LIBBASE  = libpetscsys
LOCDIR   = src/sys/draw/interface/ftn-auto/
include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test
