
#requiresdefine   'PETSC_HAVE_FORTRAN'
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = 
SOURCEF  =
SOURCEH  = petsctaolinesearch.h90 petscdmplex.h90 petscpc.h90 petscsnes.h90 petscvec.h90 petsctao.h90 petscsemilagrange.h90 petscdm.h90 petscpetscsf.h90 petscpcmg.h90 petscsnesfas.h90 petscis.h90 petscts.h90 petscdmshell.h90 petscmat.h90 petscpcexotic.h90 petscdraw.h90 petscmatorderings.h90 petscdmredundant.h90 petscpf.h90 petscpetscthreadcomm.h90 petscprofiling.h90 petscmatfd.h90 petscsys.h90 petscdmda.h90 petscdmpatch.h90 petscksp.h90 petscpcgasm.h90 petsc.h90 petscao.h90 petscviewer.h90 petscdmcomposite.h90
DIRS     =
LIBBASE   = libpetscvec
LOCDIR    = include/finclude/ftn-auto/
include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test
