
#requiresdefine   'PETSC_HAVE_FORTRAN'
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = qarnoldif.c
SOURCEF  =
SOURCEH  = 
DIRS     =
LIBBASE  = libslepcpep
LOCDIR   = src/pep/impls/qarnoldi/ftn-auto/
include ${SLEPC_DIR}/conf/slepc_common
