
#requiresdefine   'PETSC_HAVE_FORTRAN'
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = arnoldif.c
SOURCEF  =
SOURCEH  = 
DIRS     =
LIBBASE  = libslepceps
LOCDIR   = src/eps/impls/krylov/arnoldi/ftn-auto/
include ${SLEPC_DIR}/conf/slepc_common
