
#requiresdefine   'PETSC_HAVE_FORTRAN'
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = dbufff.c dlinegwf.c drectf.c dgpausef.c dpointsf.c dtrif.c dclearf.c dellipsef.c dtextgsf.c dgcoorf.c dlinewf.c dviewpf.c dpausef.c dmousef.c dsetpausef.c dlinef.c dsflushf.c drawf.c dcoorf.c drawregf.c dflushf.c dpointf.c dsclearf.c dtextsf.c
SOURCEF  =
SOURCEH  = 
DIRS     =
LIBBASE  = libpetscsys
LOCDIR   = src/sys/classes/draw/interface/ftn-auto/
include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test
