
#requiresdefine   'PETSC_HAVE_FORTRAN'
ALL: lib
CPPFLAGS  =
CFLAGS   =
FFLAGS   =
SOURCEC  = statef.c optionsf.c tagmf.c destroyf.c inheritf.c ptypef.c pinitf.c gcommf.c
SOURCEF  =
SOURCEH  = 
DIRS     =
LIBBASE	  = libpetscsys
LOCDIR	  = src/sys/objects/ftn-auto/
include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test
