
#requirespackage   'PETSC_HAVE_FORTRAN'
ALL: lib
CPPFLAGS =
CFLAGS   =
FFLAGS   =
SOURCEC  = meshf.c sectionf.c
OBJSC    = meshf.o sectionf.o
SOURCEF  =
SOURCEH  = 
DIRS     =
LIBBASE  = libpetscdm
LOCDIR   = src/dm/mesh/ftn-auto/
include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test
