#if !defined(__PETSCVERSION_H)
#define __PETSCVERSION_H

#define PETSC_VERSION_RELEASE    1
#define PETSC_VERSION_MAJOR      3
#define PETSC_VERSION_MINOR      3
#define PETSC_VERSION_SUBMINOR   0
#define PETSC_VERSION_PATCH      4
#define PETSC_VERSION_DATE       "Jun, 5, 2012"
#define PETSC_VERSION_PATCH_DATE "Fri Oct 26 10:46:51 CDT 2012"

#if !defined (PETSC_VERSION_HG)
#define PETSC_VERSION_HG         "4fbcf89a9706e19d344807f36eb71ab2c04b7df6"
#endif

#if !defined(PETSC_VERSION_DATE_HG)
#define PETSC_VERSION_DATE_HG         "Fri Oct 26 10:45:59 2012 -0500"
#endif

#define PETSC_VERSION_(MAJOR,MINOR,SUBMINOR) \
  ((PETSC_VERSION_MAJOR == (MAJOR)) &&       \
   (PETSC_VERSION_MINOR == (MINOR)) &&       \
   (PETSC_VERSION_SUBMINOR == (SUBMINOR)) && \
   (PETSC_VERSION_RELEASE  == 1))

#define PETSC_VERSION_LT(MAJOR,MINOR,SUBMINOR) \
  (PETSC_VERSION_MAJOR < (MAJOR) ||            \
   (PETSC_VERSION_MAJOR == (MAJOR) &&          \
    (PETSC_VERSION_MINOR < (MINOR) ||          \
     (PETSC_VERSION_MINOR == (MINOR) &&        \
      (PETSC_VERSION_SUBMINOR < (SUBMINOR))))))

#define PETSC_VERSION_LE(MAJOR,MINOR,SUBMINOR) \
  (PETSC_VERSION_LT(MAJOR,MINOR,SUBMINOR) || \
   PETSC_VERSION_(MAJOR,MINOR,SUBMINOR))

#endif
