
#requirespackage   'PETSC_HAVE_FORTRAN'
ALL: lib
CPPFLAGS = 
CFLAGS   =
FFLAGS   =
SOURCEC  = characteristicf.c
OBJSC    = characteristicf.o
SOURCEF  =
SOURCEH  = 
DIRS     =
LIBBASE  = libpetsccontrib
LOCDIR   = src/semiLagrange/interface/ftn-auto/
include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test
