# This will configure and build exodusii
# User can configure the source path by speficfying EXODUSII_SRC_DIR

IF ( NOT EXODUSII_SRC_DIR )
    MESSAGE(FATAL_ERROR "Please specify EXODUSII_SRC_DIR")
ENDIF()

MESSAGE("   EXODUSII_SRC_DIR = ${EXODUSII_SRC_DIR}")
FILE(MAKE_DIRECTORY "${CMAKE_INSTALL_PREFIX}/exodusii")

SET( CONFIGURE_OPTIONS "${CMAKE_ARGS};-DCMAKE_INSTALL_PREFIX=${CMAKE_INSTALL_PREFIX}/exodusii" )
SET( CONFIGURE_OPTIONS "${CONFIGURE_OPTIONS};-DHDF5HL_LIBRARY:PATH=${CMAKE_INSTALL_PREFIX}/hdf5/lib/libhdf5_hl.a" )
SET( CONFIGURE_OPTIONS "${CONFIGURE_OPTIONS};-DHDF5_LIBRARY:PATH=${CMAKE_INSTALL_PREFIX}/hdf5/lib/libhdf5.a" )
SET( CONFIGURE_OPTIONS "${CONFIGURE_OPTIONS};-DNETCDF_INCLUDE_DIR:PATH=${CMAKE_INSTALL_PREFIX}/netcdf/include" )
SET( CONFIGURE_OPTIONS "${CONFIGURE_OPTIONS};-DNETCDF_LIBRARY:PATH=${CMAKE_INSTALL_PREFIX}/netcdf/lib/libnetcdf.a" )
SET( CONFIGURE_OPTIONS "${CONFIGURE_OPTIONS};-DNETCDF_NCDUMP:PATH=${CMAKE_INSTALL_PREFIX}/netcdf/bin/ncdump" )
SET( CONFIGURE_OPTIONS "${CONFIGURE_OPTIONS};-DZ_LIBRARY:PATH=${CMAKE_INSTALL_PREFIX}/zlib/lib/libz.a" )


EXTERNALPROJECT_ADD(
    EXODUSII
    SOURCE_DIR          "${EXODUSII_SRC_DIR}"
    UPDATE_COMMAND      ""
    BUILD_IN_SOURCE     0
    INSTALL_DIR         ${CMAKE_INSTALL_PREFIX}/exodusii
    CMAKE_ARGS          "${CONFIGURE_OPTIONS}"
    BUILD_COMMAND       make install -j ${PROCS_INSTALL}
    DEPENDS             HDF5 ZLIB NETCDF
)

