# This will configure and build moab
# User can configure the source path by speficfying MOAB_SRC_DIR

IF ( NOT MOAB_SRC_DIR )
    MESSAGE(FATAL_ERROR "Please specify MOAB_SRC_DIR")
ENDIF()

MESSAGE("   MOAB_SRC_DIR = ${MOAB_SRC_DIR}")
FILE(MAKE_DIRECTORY "${CMAKE_INSTALL_PREFIX}/moab")

SET( CONFIGURE_OPTIONS QTDIR=${CMAKE_INSTALL_PREFIX}/qt )
IF ( ${CMAKE_BUILD_TYPE} STREQUAL "Debug" )
    SET( CONFIGURE_OPTIONS ${CONFIGURE_OPTIONS} --enable-debug )
ELSEIF ( ${CMAKE_BUILD_TYPE} STREQUAL "Release" )
    SET( CONFIGURE_OPTIONS ${CONFIGURE_OPTIONS} --enable-optimize )
ELSE()
    MESSAGE ( FATAL_ERROR "Unknown CMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}" )
ENDIF()
IF ( ENABLE_SHARED )
    SET( CONFIGURE_OPTIONS ${CONFIGURE_OPTIONS} --enable-shared )
ELSE()
    SET( CONFIGURE_OPTIONS ${CONFIGURE_OPTIONS} --disable-shared )
ENDIF()
IF ( ENABLE_STATIC )
    SET( CONFIGURE_OPTIONS ${CONFIGURE_OPTIONS} --enable-static )
ELSE()
    SET( CONFIGURE_OPTIONS ${CONFIGURE_OPTIONS} --disable-static )
ENDIF()

EXTERNALPROJECT_ADD(
    MOAB
    SOURCE_DIR          "${MOAB_SRC_DIR}"
    UPDATE_COMMAND      ""
    CONFIGURE_COMMAND   ${MOAB_SRC_DIR}/configure --prefix=${CMAKE_INSTALL_PREFIX}/moab ${CONFIGURE_OPTIONS} ${ENV_VARS}
    BUILD_COMMAND       make install -j ${PROCS_INSTALL}
    BUILD_IN_SOURCE     0
    INSTALL_COMMAND     ""
    DEPENDS             QT
)


