# This will configure and build parmetis
# User can configure the source path by speficfying PARMETIS_SRC_DIR

IF ( NOT PARMETIS_SRC_DIR )
    MESSAGE(FATAL_ERROR "Please specify PARMETIS_SRC_DIR")
ENDIF()

MESSAGE("   PARMETIS_SRC_DIR = ${PARMETIS_SRC_DIR}")
FILE(MAKE_DIRECTORY "${CMAKE_INSTALL_PREFIX}/parmetis")

IF ( ENABLE_SHARED AND ENABLED_STATIC )
    MESSAGE(FATAL_ERROR "Compiling parmetis with both static and shared libraries is not yet supported")
ELSEIF ( ENABLE_SHARED )
    SET( PARMETIS_CFLAGS "${CMAKE_C_FLAGS} -shared" )
    SET( PARMETIS_CXXFLAGS "${CMAKE_CXX_FLAGS} -shared" )
    SET( PARMETIS_FFLAGS "${CMAKE_Fortran_FLAGS} -shared" )
ELSEIF ( ENABLE_STATIC )
    SET( PARMETIS_CFLAGS "${CMAKE_C_FLAGS} -static" )
    SET( PARMETIS_CXXFLAGS "${CMAKE_CXX_FLAGS} -static" )
    SET( PARMETIS_FFLAGS "${CMAKE_Fortran_FLAGS} -static" )
ENDIF()
SET( PARMETIS_VARS CC=${CMAKE_C_COMPILER} CFLAGS="${PARMETIS_CFLAGS}" )
SET( PARMETIS_VARS ${PARMETIS_VARS} CXX=${CMAKE_CXX_COMPILER} CXXFLAGS=${PARMETIS_CXXFLAGS} )
SET( PARMETIS_VARS ${PARMETIS_VARS} FC=${CMAKE_Fortran_COMPILER} FCFLAGS=${PARMETIS_FFLAGS} )
SET( PARMETIS_VARS ${PARMETIS_VARS} LDFLAGS=${LDFLAGS} )


EXTERNALPROJECT_ADD(
    PARMETIS
    SOURCE_DIR          "${PARMETIS_SRC_DIR}"
    UPDATE_COMMAND      ""
    CONFIGURE_COMMAND   make distclean && make config CC=${CMAKE_C_COMPILER} CXX=${CMAKE_CXX_COMPILER} FC=${CMAKE_Fortran_COMPILER} prefix=${PARMETIS_SRC_DIR}/parmetis
    BUILD_COMMAND       make ${PARMETIS_VARS} -i
    BUILD_IN_SOURCE     1
    INSTALL_COMMAND     make install
)


