# This will configure and build sundials
# User can configure the source path by speficfying SUNDIALS_SRC_DIR
#    the download path by specifying SUNDIALS_URL, or the installed 
#    location by specifying SUNDIALS_INSTALL_DIR


# Intialize download/src/install vars
SET( SUNDIALS_BUILD_DIR "${CMAKE_BINARY_DIR}/SUNDIALS-prefix/src/SUNDIALS-build" )
IF ( SUNDIALS_URL ) 
    MESSAGE_TPL("   SUNDIALS_URL = ${SUNDIALS_URL}")
    SET( SUNDIALS_CMAKE_URL            "${SUNDIALS_URL}"        )
    SET( SUNDIALS_CMAKE_DOWNLOAD_DIR   "${SUNDIALS_BUILD_DIR}"  )
    SET( SUNDIALS_CMAKE_SOURCE_DIR     "${SUNDIALS_BUILD_DIR}"  )
    SET( SUNDIALS_CMAKE_INSTALL_DIR "${CMAKE_INSTALL_PREFIX}/sundials-${SUNDIALS_VERSION}-patched" )
    SET( CMAKE_BUILD_SUNDIALS TRUE )
ELSEIF ( SUNDIALS_SRC_DIR )
    VERIFY_PATH("${SUNDIALS_SRC_DIR}")
    MESSAGE_TPL("   SUNDIALS_SRC_DIR = ${SUNDIALS_SRC_DIR}")
    SET( SUNDIALS_CMAKE_URL                                 )
    SET( SUNDIALS_CMAKE_DOWNLOAD_DIR                        )
    SET( SUNDIALS_CMAKE_SOURCE_DIR     "${SUNDIALS_SRC_DIR}"    )
    SET( SUNDIALS_CMAKE_INSTALL_DIR "${CMAKE_INSTALL_PREFIX}/sundials-${SUNDIALS_VERSION}" )
    #SET( CMAKE_BUILD_SUNDIALS TRUE )
ELSEIF ( SUNDIALS_INSTALL_DIR ) 
    SET( SUNDIALS_CMAKE_INSTALL_DIR "${SUNDIALS_INSTALL_DIR}" )
    SET( CMAKE_BUILD_SUNDIALS FALSE )
ELSE()
    MESSAGE(FATAL_ERROR "Please specify SUNDIALS_SRC_DIR, SUNDIALS_URL, or SUNDIALS_INSTALL_DIR")
ENDIF()

FILE( APPEND "${CMAKE_INSTALL_PREFIX}/TPLs.cmake" "SET(SUNDIALS_INCLUDE_DIR \"${SUNDIALS_INCLUDE_DIR}\")\n" )
FILE( APPEND "${CMAKE_INSTALL_PREFIX}/TPLs.cmake" "SET(SUNDIALS_LIB_DIR \"${SUNDIALS_LIB_DIR}\")\n" )


FILE( MAKE_DIRECTORY "${SUNDIALS_CMAKE_INSTALL_DIR}" )
SET( SUNDIALS_INSTALL_DIR "${SUNDIALS_CMAKE_INSTALL_DIR}" )
MESSAGE_TPL( "   SUNDIALS_INSTALL_DIR = ${SUNDIALS_INSTALL_DIR}" )
FILE( APPEND "${CMAKE_INSTALL_PREFIX}/TPLs.cmake" "SET(SUNDIALS_INSTALL_DIR \"${SUNDIALS_INSTALL_DIR}\")\n" )

IF (ENABLE_SHARED)
  SET(SUNDIALS_INSTALL_CMND
#    "${PROJECT_SOURCE_DIR}/install_and_remove_static_libs.sh" "${SUNDIALS_INSTALL_DIR}")
    "")
ELSE()
  SET(SUNDIALS_INSTALL_CMND
    "${PROJECT_SOURCE_DIR}/install_and_remove_shared_libs.sh" "${SUNDIALS_INSTALL_DIR}")
ENDIF()
PRINT_VAR(SUNDIALS_INSTALL_CMND)


# Build sundials
IF ( CMAKE_BUILD_SUNDIALS ) 
    EXTERNALPROJECT_ADD(
        SUNDIALS
        URL                 "${SUNDIALS_CMAKE_URL}"
        DOWNLOAD_DIR        "${SUNDIALS_CMAKE_DOWNLOAD_DIR}"
        SOURCE_DIR          "${SUNDIALS_SRC_DIR}"
        UPDATE_COMMAND      ""
        BUILD_IN_SOURCE     0
        INSTALL_DIR         "${SUNDIALS_INSTALL_DIR}"
        CMAKE_ARGS          ${CMAKE_ARGS} -DCMAKE_INSTALL_PREFIX=${CMAKE_INSTALL_PREFIX}/sundials-${SUNDIALS_VERSION} -DFCMIX_ENABLE=ON  CFLAGS=${CMAKE_C_FLAGS} CXXFLAGS=${CMAKE_CXX_FLAGS} FFLAGS=${CMAKE_Fortran_FLAGS} FCFLAGS=${CMAKE_Fortran_FLAGS}
        BUILD_COMMAND       make -j ${PROCS_INSTALL} VERBOSE=1
        INSTALL_COMMAND     ${SUNDIALS_INSTALL_CMND}
        LOG_DOWNLOAD 1   LOG_UPDATE 1   LOG_CONFIGURE 1   LOG_BUILD 1   LOG_TEST 1   LOG_INSTALL 1
    )
    SET( SUNDIALS_INCLUDE_DIR "${SUNDIALS_INSTALL_DIR}/include")
    SET( SUNDIALS_LIB_DIR "${SUNDIALS_INSTALL_DIR}/lib")
    ADD_TPL_SAVE_LOGS( SUNDIALS )
    ADD_TPL_CLEAN( SUNDIALS )
ENDIF()

FILE( APPEND "${CMAKE_INSTALL_PREFIX}/TPLs.cmake" "SET(SUNDIALS_INCLUDE_DIR \"${SUNDIALS_INCLUDE_DIR}\")\n" )
FILE( APPEND "${CMAKE_INSTALL_PREFIX}/TPLs.cmake" "SET(SUNDIALS_LIB_DIR \"${SUNDIALS_LIB_DIR}\")\n" )

