# This will configure and build trilinos
# User can configure the source path by speficfying TRILINOS_SRC_DIR

IF ( NOT TRILINOS_SRC_DIR )
    MESSAGE(FATAL_ERROR "Please specify TRILINOS_SRC_DIR")
ENDIF()

MESSAGE("   TRILINOS_SRC_DIR = ${TRILINOS_SRC_DIR}")
FILE(MAKE_DIRECTORY "${CMAKE_INSTALL_PREFIX}/trilinos")

SET( CONFIGURE_OPTIONS "${CMAKE_ARGS};-DCMAKE_INSTALL_PREFIX=${CMAKE_INSTALL_PREFIX}/trilinos" )
SET( CONFIGURE_OPTIONS "${CONFIGURE_OPTIONS};-DTPL_ENABLE_MPI:BOOL=ON" )
SET( CONFIGURE_OPTIONS "${CONFIGURE_OPTIONS};-DTrilinos_ENABLE_Epetra:BOOL=ON" )
SET( CONFIGURE_OPTIONS "${CONFIGURE_OPTIONS};-DTrilinos_ENABLE_EpetraExt:BOOL=ON" )
SET( CONFIGURE_OPTIONS "${CONFIGURE_OPTIONS};-DTrilinos_ENABLE_Tpetra:BOOL=ON" )
SET( CONFIGURE_OPTIONS "${CONFIGURE_OPTIONS};-DTrilinos_ENABLE_Teuchos:BOOL=OFF" )
SET( CONFIGURE_OPTIONS "${CONFIGURE_OPTIONS};-DTrilinos_ENABLE_Kokkos:BOOL=OFF" )
SET( CONFIGURE_OPTIONS "${CONFIGURE_OPTIONS};-DTrilinos_ENABLE_AztecOO:BOOL=OFF" )
SET( CONFIGURE_OPTIONS "${CONFIGURE_OPTIONS};-DTrilinos_ENABLE_ML:BOOL=OFF" )
SET( CONFIGURE_OPTIONS "${CONFIGURE_OPTIONS};-DTrilinos_ENABLE_NOX:BOOL=OFF" )
SET( CONFIGURE_OPTIONS "${CONFIGURE_OPTIONS};-DTrilinos_ENABLE_Amesos:BOOL=OFF" )
SET( CONFIGURE_OPTIONS "${CONFIGURE_OPTIONS};-DTrilinos_ENABLE_TESTS:BOOL=OFF" )
SET( CONFIGURE_OPTIONS "${CONFIGURE_OPTIONS};-DTrilinos_ENABLE_PERFORMANCE_TESTS:BOOL=OFF" )
SET( CONFIGURE_OPTIONS "${CONFIGURE_OPTIONS};-DTrilinos_ENABLE_Fortran:BOOL=ON" )
SET( CONFIGURE_OPTIONS "${CONFIGURE_OPTIONS};-DTrilinos_ENABLE_Ifpack:BOOL=OFF" )
SET( CONFIGURE_OPTIONS "${CONFIGURE_OPTIONS};-DTrilinos_ENABLE_Zoltan:BOOL=ON" )
SET( CONFIGURE_OPTIONS "${CONFIGURE_OPTIONS};-DTPL_BLAS_LIBRARIES:STRING=${CMAKE_INSTALL_PREFIX}/lapack/lib/libblas.a" )
SET( CONFIGURE_OPTIONS "${CONFIGURE_OPTIONS};-DTPL_LAPACK_LIBRARIES:STRING=${CMAKE_INSTALL_PREFIX}/lapack/lib/liblapack.a" )


EXTERNALPROJECT_ADD(
    TRILINOS
    SOURCE_DIR          "${TRILINOS_SRC_DIR}"
    UPDATE_COMMAND      ""
    BUILD_IN_SOURCE     0
    INSTALL_DIR         ${CMAKE_INSTALL_PREFIX}/trilinos
    CMAKE_ARGS          "${CONFIGURE_OPTIONS}"
    BUILD_COMMAND       make install -j ${PROCS_INSTALL}
    DEPENDS             LAPACK
)

