# This will configure and build zlib
# User can configure the source path by speficfying ZLIB_SRC_DIR
#    the download path by specifying ZLIB_URL, or the installed 
#    location by specifying ZLIB_INSTALL_DIR


# Intialize download/src/install vars
SET( ZLIB_BUILD_DIR "${CMAKE_BINARY_DIR}/ZLIB-prefix/src/ZLIB-build" )
IF ( ZLIB_URL ) 
    MESSAGE_TPL("   ZLIB_URL = ${ZLIB_URL}")
    SET( ZLIB_CMAKE_URL            "${ZLIB_URL}"        )
    SET( ZLIB_CMAKE_DOWNLOAD_DIR   "${ZLIB_BUILD_DIR}"  )
    SET( ZLIB_CMAKE_SOURCE_DIR     "${ZLIB_BUILD_DIR}"  )
    SET( ZLIB_CMAKE_INSTALL_DIR "${CMAKE_INSTALL_PREFIX}/zlib-${ZLIB_VERSION}-patched" )
    SET( CMAKE_BUILD_ZLIB TRUE )
ELSEIF ( ZLIB_SRC_DIR )
    VERIFY_PATH("${ZLIB_SRC_DIR}")
    MESSAGE_TPL("   ZLIB_SRC_DIR = ${ZLIB_SRC_DIR}")
    SET( ZLIB_CMAKE_URL                                 )
    SET( ZLIB_CMAKE_DOWNLOAD_DIR                        )
    SET( ZLIB_CMAKE_SOURCE_DIR     "${ZLIB_SRC_DIR}"    )
    SET( ZLIB_CMAKE_INSTALL_DIR "${CMAKE_INSTALL_PREFIX}/zlib-${ZLIB_VERSION}" )
    #SET( CMAKE_BUILD_ZLIB TRUE )
ELSEIF ( ZLIB_INSTALL_DIR ) 
    SET( ZLIB_CMAKE_INSTALL_DIR "${ZLIB_INSTALL_DIR}" )
    SET( CMAKE_BUILD_ZLIB FALSE )
ELSE()
    MESSAGE(FATAL_ERROR "Please specify ZLIB_SRC_DIR, ZLIB_URL, or ZLIB_INSTALL_DIR")
ENDIF()

IF (BUILD_SERIAL_TPLS)
FILE( MAKE_DIRECTORY "${ZLIB_CMAKE_INSTALL_DIR}_serial" )
SET( ZLIB_INSTALL_DIR "${ZLIB_CMAKE_INSTALL_DIR}_serial" )
MESSAGE_TPL( "   ZLIB_INSTALL_DIR = ${ZLIB_INSTALL_DIR}" )
FILE( APPEND "${CMAKE_INSTALL_PREFIX}/TPLs.cmake" "SET(ZLIB_INSTALL_DIR \"${ZLIB_INSTALL_DIR}\")\n" )

IF (ENABLE_SHARED)
  SET(ZLIB_INSTALL_CMND
    "${PROJECT_SOURCE_DIR}/install_and_remove_static_libs.sh" "${ZLIB_INSTALL_DIR}")
ELSE()
  SET(ZLIB_INSTALL_CMND
    "${PROJECT_SOURCE_DIR}/install_and_remove_shared_libs.sh" "${ZLIB_INSTALL_DIR}")
ENDIF()
PRINT_VAR(ZLIB_INSTALL_CMND)

# Build zlib
IF ( CMAKE_BUILD_ZLIB ) 
    EXTERNALPROJECT_ADD(
        ZLIB
        URL                 "${ZLIB_CMAKE_URL}"
        DOWNLOAD_DIR        "${ZLIB_CMAKE_DOWNLOAD_DIR}"
        SOURCE_DIR          "${ZLIB_SRC_DIR}"
        UPDATE_COMMAND      ""
        BUILD_IN_SOURCE     0
        INSTALL_DIR         "${ZLIB_INSTALL_DIR}"
        CMAKE_ARGS          ${CMAKE_ARGS} -DCMAKE_INSTALL_PREFIX=${CMAKE_INSTALL_PREFIX}/zlib-${ZLIB_VERSION}_serial
        BUILD_COMMAND       make -j ${PROCS_INSTALL} VERBOSE=1
        INSTALL_COMMAND     ${ZLIB_INSTALL_CMND}
        LOG_DOWNLOAD 1   LOG_UPDATE 1   LOG_CONFIGURE 1   LOG_BUILD 1   LOG_TEST 1   LOG_INSTALL 1
    )
    SET( ZLIB_INCLUDE_DIR "${ZLIB_INSTALL_DIR}/include")
    SET( ZLIB_LIB_DIR "${ZLIB_INSTALL_DIR}/lib")
    ADD_TPL_SAVE_LOGS( ZLIB )
    ADD_TPL_CLEAN( ZLIB )
ENDIF()
ELSE()
FILE( APPEND "${CMAKE_INSTALL_PREFIX}/TPLs.cmake" "SET(ZLIB_INCLUDE_DIR \"${ZLIB_INCLUDE_DIR}\")\n" )
FILE( APPEND "${CMAKE_INSTALL_PREFIX}/TPLs.cmake" "SET(ZLIB_LIB_DIR \"${ZLIB_LIB_DIR}\")\n" )


FILE( MAKE_DIRECTORY "${ZLIB_CMAKE_INSTALL_DIR}" )
SET( ZLIB_INSTALL_DIR "${ZLIB_CMAKE_INSTALL_DIR}" )
MESSAGE_TPL( "   ZLIB_INSTALL_DIR = ${ZLIB_INSTALL_DIR}" )
FILE( APPEND "${CMAKE_INSTALL_PREFIX}/TPLs.cmake" "SET(ZLIB_INSTALL_DIR \"${ZLIB_INSTALL_DIR}\")\n" )

IF (ENABLE_SHARED)
  SET(ZLIB_INSTALL_CMND
    "${PROJECT_SOURCE_DIR}/install_and_remove_static_libs.sh" "${ZLIB_INSTALL_DIR}")
ELSE()
  SET(ZLIB_INSTALL_CMND
    "${PROJECT_SOURCE_DIR}/install_and_remove_shared_libs.sh" "${ZLIB_INSTALL_DIR}")
ENDIF()
PRINT_VAR(ZLIB_INSTALL_CMND)


# Build zlib
IF ( CMAKE_BUILD_ZLIB ) 
    EXTERNALPROJECT_ADD(
        ZLIB
        URL                 "${ZLIB_CMAKE_URL}"
        DOWNLOAD_DIR        "${ZLIB_CMAKE_DOWNLOAD_DIR}"
        SOURCE_DIR          "${ZLIB_SRC_DIR}"
        UPDATE_COMMAND      ""
        BUILD_IN_SOURCE     0
        INSTALL_DIR         "${ZLIB_INSTALL_DIR}"
        CMAKE_ARGS          ${CMAKE_ARGS} -DCMAKE_INSTALL_PREFIX=${CMAKE_INSTALL_PREFIX}/zlib-${ZLIB_VERSION}
        BUILD_COMMAND       make -j ${PROCS_INSTALL} VERBOSE=1
        INSTALL_COMMAND     ${ZLIB_INSTALL_CMND}
        LOG_DOWNLOAD 1   LOG_UPDATE 1   LOG_CONFIGURE 1   LOG_BUILD 1   LOG_TEST 1   LOG_INSTALL 1
    )
    SET( ZLIB_INCLUDE_DIR "${ZLIB_INSTALL_DIR}/include")
    SET( ZLIB_LIB_DIR "${ZLIB_INSTALL_DIR}/lib")
    ADD_TPL_SAVE_LOGS( ZLIB )
    ADD_TPL_CLEAN( ZLIB )
ENDIF()

FILE( APPEND "${CMAKE_INSTALL_PREFIX}/TPLs.cmake" "SET(ZLIB_INCLUDE_DIR \"${ZLIB_INCLUDE_DIR}\")\n" )
FILE( APPEND "${CMAKE_INSTALL_PREFIX}/TPLs.cmake" "SET(ZLIB_LIB_DIR \"${ZLIB_LIB_DIR}\")\n" )
ENDIF()
