
#requiresdefine   'PETSC_HAVE_FORTRAN'
ALL: lib
CPPFLAGS =
CFLAGS   =
FFLAGS   =
SOURCEC  = networkf.c networkcreatef.c
SOURCEF  =
SOURCEH  = 
DIRS     =
LIBBASE  = libpetscdm
LOCDIR   = src/dm/impls/network/ftn-auto/
include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test
