
#requirespackage   'PETSC_HAVE_FORTRAN'
ALL: lib
CPPFLAGS  = 
CFLAGS   =
FFLAGS   =
SOURCEC  = signalf.c fpf.c adebugf.c errf.c
OBJSC    = signalf.o fpf.o adebugf.o errf.o
SOURCEF  =
SOURCEH  = 
DIRS     =
LIBBASE	  = libpetscsys
LOCDIR	  = src/sys/error/ftn-auto/
include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test
