
#requiresdefine   'PETSC_HAVE_FORTRAN'
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = taosolver_boundsf.c taosolver_fgf.c taosolver_hjf.c taosolverf.c
SOURCEF  =
SOURCEH  = 
DIRS     =
LIBBASE  = libpetsctao
LOCDIR   = src/tao/interface/ftn-auto/
include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test
