
#requirespackage   'PETSC_HAVE_FORTRAN'
ALL: lib
CPPFLAGS  =
CFLAGS   =
FFLAGS   =
SOURCEC  = mprintf.c sysiof.c mpiuopenf.c
OBJSC    = mprintf.o sysiof.o mpiuopenf.o
SOURCEF  =
SOURCEH  = 
DIRS     =
LIBBASE	  = libpetscsys
LOCDIR	  = src/sys/fileio/ftn-auto/
include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test
