
#requiresdefine   'PETSC_HAVE_FORTRAN'
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = svdsolvef.c svdmonf.c svdbasicf.c svdsetupf.c svdoptsf.c
SOURCEF  =
SOURCEH  = 
DIRS     =
LIBBASE  = libslepcsvd
LOCDIR   = src/svd/interface/ftn-auto/
include ${SLEPC_DIR}/conf/slepc_common
