
#requirespackage   'PETSC_HAVE_FORTRAN'
ALL: lib
CPPFLAGS = ${JOSTLE_INCLUDE}
CFLAGS   =
FFLAGS   =
SOURCEC  = jostlef.c
OBJSC    = jostlef.o
SOURCEF  =
SOURCEH  = 
DIRS     =
LIBBASE  = libpetscmat
LOCDIR   = src/mat/partition/impls/jostle/ftn-auto/
include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test
