
#requiresdefine   'PETSC_HAVE_FORTRAN'
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = sff.c
SOURCEF  =
SOURCEH  = 
DIRS     =
LIBBASE	 = libpetscvec
LOCDIR   = src/vec/is/sf/interface/ftn-auto/
include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test
