
#requiresdefine   'PETSC_HAVE_FORTRAN'
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = stsetf.c stfuncf.c stslesf.c stsolvef.c
SOURCEF  =
SOURCEH  = 
DIRS     =
LIBBASE  = libslepcsys
LOCDIR   = src/sys/classes/st/interface/ftn-auto/
include ${SLEPC_DIR}/conf/slepc_common
