
#requiresdefine   'PETSC_HAVE_FORTRAN'
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = aijcuspf.c
SOURCEF  =
SOURCEH  = 
DIRS     =
LIBBASE   = libpetscmat
LOCDIR    = src/mat/impls/aij/seq/seqcusp/ftn-auto/
include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test
