
#requiresdefine   'PETSC_HAVE_FORTRAN'
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = dalocalf.c dacreatef.c dagetarrayf.c dageometryf.c daghostf.c dadistf.c dagtolf.c dagtonaf.c daddf.c dacornf.c dapreallocatef.c dainterpf.c daf.c fddaf.c gr1f.c daindexf.c
SOURCEF  =
SOURCEH  = 
DIRS     =
LIBBASE  = libpetscdm
LOCDIR   = src/dm/impls/da/ftn-auto/
include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test
