
#requirespackage   'PETSC_HAVE_FORTRAN'
ALL: lib
CPPFLAGS  = 
CFLAGS   =
FFLAGS   =
SOURCEC  = optionsf.c destroyf.c ptypef.c tagmf.c inheritf.c pinitf.c
OBJSC    = optionsf.o destroyf.o ptypef.o tagmf.o inheritf.o pinitf.o
SOURCEF  =
SOURCEH  = 
DIRS     =
LIBBASE	  = libpetscsys
LOCDIR	  = src/sys/objects/ftn-auto/
include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test
