
#requirespackage   'PETSC_HAVE_FORTRAN'
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = 
OBJSC    = 
SOURCEF  =
SOURCEH  = petscvec.h90 petscis.h90 petscpf.h90 petscmat.h90 petscao.h90 petscksp.h90 petscmatorderings.h90 petscsnes.h90 petscts.h90 petscsys.h90 petscsemilagrange.h90 petscdraw.h90 petscviewer.h90 petscprofiling.h90 petscmatfd.h90 petscda.h90 petscmesh.h90 petscpc.h90
DIRS     =
LIBBASE   = libpetscvec
LOCDIR    = include/finclude/ftn-auto/
include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test
