#!/usr/bin/sh

   export COMP_USE="gcc-4.6.1"
   export TYPE="gcc"
   export PACKAGE_NUMBER="gcc461"
   export COMPARE_NUMBER="461"
   export CC_BASE=gcc
   export CXX_BASE=g++
   export FC_BASE=gfortran
   export TPL_INSTALL_DIR=/projects/vera/gcc-4.6.1
   export PLATFORM=linux-gnu
   export PETSC_ARCH=${PLATFORM}-$METHOD
   export TRILINOS_DIR=$TPL_INSTALL_DIR/../Trilinos
   export HYDRATH_TRILINOS_DIR=$TPL_INSTALL_DIR/../Trilinos
   export PATH=$PATH:.
   export HDF5_VERSION=hdf5-1.8.7
   export SILO_VERSION=silo-4.8
   export QT_VERSION=qt-everywhere-opensource-src-4.8.2
   export OPENMPI_VERSION=openmpi-1.4.3
   export TRILINOS_VERSION=Trilinos
   export ZLIB_VERSION=zlib-1.2.5-patched
   export HDF5_VERSION=hdf5-1.8.7
   export NETCDF_VERSION=netcdf-4.1.3
   export EXODUS_VERSION=exodusii-5.14-patched
   export PARMETIS_VERSION=parmetis-4.0.2-patched
   export CHACO_VERSION=Chaco-2.2-patched
   export PETSC_VERSION=petsc-3.1-p8
   export ML_VERSION=ml-6.2
   export HYDRATH_TRILINOS_VERSION=Trilinos
   export LAPACK_VERSION=lapack-3.3.1
   export BOOST_VERSION=boost-1.49.0
   export CMAKE_VERSION=cmake-2.8.5
   export GCC_VERSION=gcc-4.6.1
   export OPENMPI_VER=1.4.3
   export HDF5_VER=1.8.7
   export SILO_VER=4.8
   export QT_VER=4.8.2
   export ZLIB_VER=1.2.5-patched
   export NETCDF_VER=4.1.3
   export EXODUS_VER=5.14-patched
   export PARMETIS_VERSION=4.0.2-patched
   export CHACO_VER=2.2-patched
   export PETSC_VER=3.1-p8
   export ML_VER=6.2
   export HYDRATH_TRILINOS_VERSION=Trilinos
   export LAPACK_VER=3.3.1
   export BOOST_VER=1.49.0
   export CMAKE_VER=2.8.5
   export GCC_VER=4.6.1
   export COMPILE_MODE=optimized
   export CFLAGS="-O2 -fPIC"
   export CXXFLAGS="-O2 -fPIC"
   export FCFLAGS="-O2 -fPIC"
   export DEBUG_BOOL="FALSE"
   export GCC_DIR=${TPL_INSTALL_DIR}/toolset/gcc
   export PATH=${GCC_DIR}/bin:$PATH
   export LD_LIBRARY_PATH=${GCC_DIR}/lib64:$LD_LIBRARY_PATH
   export OPENMPI_DIR=${TPL_INSTALL_DIR}/toolset/openmpi
   export PATH=${OPENMPI_DIR}/bin:$PATH 
   export LD_LIBRARY_PATH=${OPENMPI_DIR}/lib:$LD_LIBRARY_PATH
   export CMAKE_DIR=${TPL_INSTALL_DIR}/toolset/cmake
   export PATH=${CMAKE_DIR}/bin:${PATH}
   export BOOST_DIR=${TPL_INSTALL_DIR}/toolset/boost-${BOOST_VER}

