
#requiresdefine   'PETSC_HAVE_FORTRAN'
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = bvbasicf.c bvorthogf.c bvopsf.c bvglobalf.c bvfuncf.c
SOURCEF  =
SOURCEH  = 
DIRS     =
LIBBASE  = libslepcsys
LOCDIR   = src/sys/classes/bv/interface/ftn-auto/
include ${SLEPC_DIR}/conf/slepc_common
