
#requiresdefine   'PETSC_HAVE_FORTRAN'
ALL: lib
CPPFLAGS =
CFLAGS   =
FFLAGS   =
SOURCEC  = plexfemf.c plexcreatef.c plexrefinef.c plexexodusiif.c plexcgnsf.c plexindicesf.c plexlabelf.c plexf.c plexdistributef.c plexinterpolatef.c plexpointf.c plexgmshf.c plexsubmeshf.c plexreorderf.c
SOURCEF  =
SOURCEH  = 
DIRS     =
LIBBASE  = libpetscdm
LOCDIR   = src/dm/impls/plex/ftn-auto/
include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test
