
#requiresdefine   'PETSC_HAVE_FORTRAN'
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = taolinesearchf.c
SOURCEF  =
SOURCEH  = 
DIRS     =
LIBBASE  = libpetsctao
LOCDIR   = src/tao/linesearch/interface/ftn-auto/
include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test
