
#requiresdefine   'PETSC_HAVE_FORTRAN'
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = dsopsf.c dsbasicf.c
SOURCEF  =
SOURCEH  = 
DIRS     =
LIBBASE  = libslepcsys
LOCDIR   = src/sys/classes/ds/interface/ftn-auto/
include ${SLEPC_DIR}/conf/slepc_common
