
#requirespackage   'PETSC_HAVE_FORTRAN'
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = da2f.c dacornf.c daf.c dainterpf.c dagetarrayf.c dadestroyf.c dacreatef.c dalocalf.c dadistf.c dagtolf.c daindexf.c dagtonaf.c daltolf.c gr1f.c daltogf.c daghostf.c
OBJSC    = da2f.o dacornf.o daf.o dainterpf.o dagetarrayf.o dadestroyf.o dacreatef.o dalocalf.o dadistf.o dagtolf.o daindexf.o dagtonaf.o daltolf.o gr1f.o daltogf.o daghostf.o
SOURCEF  =
SOURCEH  = 
DIRS     =
LIBBASE  = libpetscdm
LOCDIR   = src/dm/da/src/ftn-auto/
include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test
