
#requirespackage   'PETSC_HAVE_FORTRAN'
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = viewregf.c flushf.c viewf.c duplf.c
OBJSC    = viewregf.o flushf.o viewf.o duplf.o
SOURCEF  =
SOURCEH  = 
DIRS     =
LIBBASE  = libpetscsys
LOCDIR   = src/sys/viewer/interface/ftn-auto/
include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test
