
#requiresdefine   'PETSC_HAVE_FORTRAN'
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = isblockf.c isdifff.c iscompf.c iscoloringf.c
SOURCEF  =
SOURCEH  = 
DIRS     =
LIBBASE	 = libpetscvec
LOCDIR	 = src/vec/is/is/utils/ftn-auto/
include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test
