
#requiresdefine   'PETSC_HAVE_FORTRAN'
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = slepcscf.c slepcutilf.c slepcinitf.c
SOURCEF  =
SOURCEH  = 
DIRS     =
LIBBASE  = libslepcsys
LOCDIR   = src/sys/ftn-auto/
include ${SLEPC_DIR}/conf/slepc_common
